name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libboost-all-dev libssl-dev libxml2-dev libtool autoconf automake
          sudo apt install -y libpoco-dev

      - name: Build Fix8 with suppressed warnings
        run: |
          git clone https://github.com/fix8/fix8.git
          cd fix8
          echo "Fix8 directory contents:"
          ls -la
          
          echo "Running bootstrap..."
          ./bootstrap
          
          echo "Configuring Fix8..."
          # Configure with suppressed warnings for cleaner CI output
          CXXFLAGS="-Wno-class-memaccess -Wno-unused-result -Wno-overloaded-virtual -Wno-deprecated-declarations" ./configure --prefix=/usr/local
          
          echo "Building Fix8..."
          make -j$(nproc)
          
          echo "Installing Fix8..."
          sudo make install
          sudo ldconfig
          
          echo "Fix8 installation completed. Checking installation:"
          ls -la /usr/local/include/fix8/ || echo "Headers not in /usr/local/include/fix8/"
          ls -la /usr/local/lib/libfix8* || echo "Libraries not in /usr/local/lib/"

      - name: Verify Fix8 installation
        run: |
          chmod +x verify_fix8.sh
          ./verify_fix8.sh

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Run smoke test
        run: |
          cd build
          ./test_smoke
