name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libboost-all-dev libssl-dev libxml2-dev

      - name: Build Fix8
        run: |
          git clone --depth=1 https://github.com/fix8/fix8.git
          cd fix8
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Run smoke test
        run: ./tests/test_smoke
